In [18]:
import numpy as np

# User input for matrix order
n = int(input("Enter the order of the square matrix ( 2 for 2x2, 3 for 3x3): "))

# User input for matrix elements
print(f"Enter {n*n} elements for the matrix row-wise:")

elements = []
for i in range(n*n):
    val = int(input(f"Element {i+1}: "))
    elements.append(val)

# Create NumPy array and reshape it into n x n matrix
matrix = np.array(elements).reshape(n, n)

print("\nThe matrix is:")
print(matrix)

# Calculate sum of diagonal elements using a loop
diagonal_sum = 0
for i in range(n):
    diagonal_sum += matrix[i][i]

# Output the sum
print(f"\nThe sum of diagonal elements is: {diagonal_sum}")


Enter the order of the square matrix ( 2 for 2x2, 3 for 3x3):  3


Enter 9 elements for the matrix row-wise:


Element 1:  2
Element 2:  4
Element 3:  5
Element 4:  6
Element 5:  1
Element 6:  3
Element 7:  7
Element 8:  2
Element 9:  4



The matrix is:
[[2 4 5]
 [6 1 3]
 [7 2 4]]

The sum of diagonal elements is: 7


In [19]:
import sqlite3
import pandas as pd

# Connect to SQLite in-memory database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create tables
cursor.execute('''
CREATE TABLE Student (
    RollNo INTEGER PRIMARY KEY,
    Name TEXT,
    Marks INTEGER,
    Aadhar_Number TEXT UNIQUE,
    Address TEXT
)
''')

cursor.execute('''
CREATE TABLE Course (
    RollNo INTEGER,
    Course TEXT,
    Course_Duration TEXT,
    FOREIGN KEY (RollNo) REFERENCES Student(RollNo)
)
''')

# Insert data
students = [
    (1, 'Rahul', 25, '123456789012', 'Delhi'),
    (2, 'Anjali', 85, '123456789013', 'Mumbai'),
    (3, 'Rohit', 40, '123456789014', 'Bangalore'),
    (4, 'Reena', 95, '123456789015', 'Chennai'),
    (5, 'Amit', 28, '123456789016', 'Kolkata')
]
cursor.executemany('INSERT INTO Student VALUES (?, ?, ?, ?, ?)', students)

courses = [
    (1, 'BCA', '3 years'),
    (2, 'MCA', '2 years'),
    (3, 'BBA', '3 years'),
    (4, 'BCA', '3 years'),
    (5, 'BCA', '3 years')
]
cursor.executemany('INSERT INTO Course VALUES (?, ?, ?)', courses)

conn.commit()

# Example query: average marks
df = pd.read_sql_query('SELECT AVG(Marks) AS Average_Marks FROM Student', conn)
print("Average marks:")
print(df)

# Names ascending
df = pd.read_sql_query('SELECT Name FROM Student ORDER BY Name ASC', conn)
print("Students names in ascending order:")
print(df)

# Students scoring below 30
df = pd.read_sql_query('SELECT RollNo, Name FROM Student WHERE Marks < 30', conn)
print("students rollno who scored below 30:")
print(df)

# Names starting with 'R'
df = pd.read_sql_query("SELECT RollNo FROM Student WHERE Name LIKE 'R%'", conn)
print("Students rollno whose name start with R:")
print(df)

# RollNos pursuing BCA
df = pd.read_sql_query("SELECT RollNo FROM Course WHERE Course = 'BCA'", conn)
print("Students rollno who are pursuing :")
print(df)

conn.close()


Average marks:
   Average_Marks
0           54.6
Students names in ascending order:
     Name
0    Amit
1  Anjali
2   Rahul
3   Reena
4   Rohit
students rollno who scored below 30:
   RollNo   Name
0       1  Rahul
1       5   Amit
Students rollno whose name start with R:
   RollNo
0       1
1       3
2       4
Students rollno who are pursuing :
   RollNo
0       1
1       4
2       5
